=== s72785/notes/i465/xml/katalog.dtd
<!--
	status:draft
-->
<!--
*********************
	ENTITIES
*********************
	-->

<!ENTITY % buch.lang "
de, en
">

<!ENTITY % container.format "
quader, zylinder, daten
">
<!--

<!ENTITY % abmessung.einheit "
mm, in
">
<!ENTITY % gewicht.einheit "
g, oz
">
-->
<!--
*********************
	NOTATIONS
*********************
	-->

<!NOTATION g SYSTEM "Buch/Gewicht/Gramm">
<!NOTATION oz SYSTEM "Buch/Gewicht/Unze">

<!NOTATION daten SYSTEM "Buch/Format/Daten">
<!NOTATION quader SYSTEM "Buch/Format/Quader">
<!NOTATION zylinder SYSTEM "Buch/Format/Zylinder">

<!NOTATION mm SYSTEM "Buch/Abmessung/Millimeter">
<!NOTATION in SYSTEM "Buch/Abmessung/Zoll">

<!NOTATION GIF SYSTEM "image/gif">

<!NOTATION JPG SYSTEM "image/jpeg">

<!NOTATION PNG SYSTEM "image/png">

<!--
*********************
	DECLARATIONS
*********************
	-->

<!ELEMENT katalog (buch | datentraeger | hoerbuch)*>
<!ATTLIST katalog
  name    CDATA    #IMPLIED
  >
<!ELEMENT datentraeger (#PCDATA)>
<!ATTLIST datentraeger
  lang    NMTOKEN  "de"
  >
<!ELEMENT hoerbuch (#PCDATA)>
<!ATTLIST hoerbuch
  lang    NMTOKEN  "de"
  >
<!ELEMENT id (#PCDATA)*>
<!ATTLIST id
  name    CDATA    #IMPLIED
  >
<!ELEMENT buch (titel, id, autor, verlag, preisdaten, lager, gewicht, (kurzinhalt | container | bild)*)>
<!ATTLIST buch
  lang    NMTOKEN  "de"
  >
<!ELEMENT titel (#PCDATA)>
<!ATTLIST titel
  lang    CDATA    #IMPLIED
  >
<!ELEMENT autor (#PCDATA)>
<!ATTLIST autor
  id      CDATA    #REQUIRED
  type    CDATA    #IMPLIED
  order   CDATA    #IMPLIED
  >
<!ELEMENT verlag (#PCDATA)>
<!ATTLIST verlag
  id      CDATA    #REQUIRED
  >
<!ELEMENT preisdaten (#PCDATA)>
<!ATTLIST preisdaten
  netto   CDATA    #REQUIRED
  brutto  CDATA    #IMPLIED
  ust     CDATA    #IMPLIED
  >
<!ELEMENT lager (#PCDATA)>
<!ATTLIST lager
  name    CDATA    #IMPLIED
  id      CDATA    #IMPLIED
  einheit CDATA    #IMPLIED
  >
<!ELEMENT gewicht (#PCDATA)>
<!ATTLIST gewicht
  einheit NOTATION (g | oz) "g"
  >
<!ELEMENT kurzinhalt (#PCDATA)>
<!ELEMENT container (abmessung | dateigroesse)*>
<!ATTLIST container
  format  NOTATION  (quader | zylinder | daten) "daten"
  >
<!ELEMENT dateigroesse (#PCDATA)>
<!ELEMENT abmessung (#PCDATA)>
<!ATTLIST abmessung 
  name    CDATA    #REQUIRED
  einheit NOTATION (mm | in) "mm"
  >
<!ELEMENT bild (grafik)+>
<!ELEMENT grafik (#PCDATA)>
<!ATTLIST grafik
  src     CDATA    #IMPLIED
  >

<!--

Wissens-Quelle:
http://www.data2type.de/xml-xslt-xslfo/xml/xml-in-a-nutshell/dokumenttyp-definitionen/

-->

=== s72785/notes/i465/xml/katalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE katalog SYSTEM "katalog.dtd">

<katalog>
	<buch>
		<titel lang="de">Enigma</titel>
		<id name="isbn">9876543245</id>
		<autor id="" typ="writer" order="1"></autor>
		<verlag id=""></verlag>
		<preisdaten netto="" brutto="" ust=""></preisdaten>
		<lager id="" name="">123</lager>
		<gewicht einheit="g">123</gewicht>

		<kurzinhalt>Beschreibung</kurzinhalt>
		<container format="quader">
			<abmessung name="laenge" einheit="mm">10</abmessung>
			<abmessung name="breite" einheit="mm">15</abmessung>
			<abmessung name="hoehe" einheit="mm">5</abmessung>
		</container>
		<bild>
			<grafik src="./x.jpg"/>
		</bild>
	</buch>
	<buch>
		<titel lang="de">Enigma2</titel>
		<id name="isbn">9876545695</id>
		<autor id="" typ="writer" order="1"></autor>
		<verlag id=""></verlag>
		<preisdaten netto="10" ust=""></preisdaten>
		<lager id="" name="">123</lager>
		<gewicht einheit="g">123</gewicht>

		<kurzinhalt>Beschreibung</kurzinhalt>
		<container format="quader">
			<abmessung name="laenge" einheit="cm">7</abmessung>
			<abmessung name="breite" einheit="cm">4</abmessung>
			<abmessung name="hoehe" einheit="cm">3</abmessung>
		</container>
		<bild>
			<grafik src="./x.jpg"/>
		</bild>
	</buch>
</katalog>

=== s72785/notes/i465/xml/katalog2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE katalog SYSTEM "katalog.dtd">-->

<katalog
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="katalog.xsd">
>
	<buch>
<!-- req -->
		<titel lang="de">Enigma</titel>
		<id name="isbn">9876543245</id>
		<autor id="" typ="writer" order="1"></autor>
		<verlag id=""></verlag>
		<preisdaten netto="90" ust="19"/>
		<lager id="" name="">123</lager>
		<gewicht einheit="g">123</gewicht>
<!-- opt -->
		<kurzinhalt>Beschreibung</kurzinhalt>
		<container format="quader">
			<abmessung name="laenge" einheit="mm">10</abmessung>
			<abmessung name="breite" einheit="mm">15</abmessung>
			<abmessung name="hoehe" einheit="mm">5</abmessung>
		</container>
		<bild>
			<grafik src="./x.jpg"/>
		</bild>
	</buch>
	<buch>
		<titel lang="de">Enigma2</titel>
		<id name="isbn">9876545695</id>
		<autor id="" typ="writer" order="1"></autor>
		<verlag id=""></verlag>
		<preisdaten netto="10" ust="19"></preisdaten>
		<lager id="" name="">123</lager>
		<gewicht einheit="g">123</gewicht>

		<kurzinhalt>Beschreibung</kurzinhalt>
		<container format="quader">
			<abmessung name="laenge" einheit="cm">7</abmessung>
			<abmessung name="breite" einheit="cm">4</abmessung>
			<abmessung name="hoehe" einheit="cm">3</abmessung>
		</container>
		<bild>
			<grafik src="./x.jpg"/>
		</bild>
	</buch>
</katalog>
